Mongodb.Web/Models/Aggregate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mongodb.Web.Models
{
    public class Aggregate
    {
        public string BookName { get; set; }
        public decimal Total { get; set; }
    }
}

Mongodb.Web/Models/Book.cs
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mongodb.Web.Models
{
    public class Book
    {
        [BsonId]       
        public string Id { get; set; }

        [BsonElement("Name")]
        public string BookName { get; set; }

        public decimal Price { get; set; }

        public string Category { get; set; }

        public string Author { get; set; }
    }
}

Mongodb.Web/Models/BookstoreDatabaseSettings.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mongodb.Web.Models
{
    public class BookstoreDatabaseSettings : IBookstoreDatabaseSettings
    {
        public string BooksCollectionName { get; set; }
        public string ConnectionString { get; set; }
        public string DatabaseName { get; set; }
    }

    public interface IBookstoreDatabaseSettings
    {
        string BooksCollectionName { get; set; }
        string ConnectionString { get; set; }
        string DatabaseName { get; set; }
    }
}

Mongodb.Web/Models/ErrorViewModel.cs
using System;

namespace Mongodb.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Mongodb.Web/Controllers/BinaryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Mongodb.Web.Controllers
{
    public class BinaryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult CheckValidBinaryString([FromBody] string binaryStr)
        {
            if (!string.IsNullOrEmpty(binaryStr))
            {
                var result = CheckForGoodBinaryString(binaryStr);
                return Json(result);
            }
            return Json("Please enter a valid string");
        }

        private string CheckForGoodBinaryString(string inputStr)
        {
            Regex rgx = new Regex(@"^[01]+$");
            long noOfZeros = 0;
            long noOfOnes = 0;
            List<string> prefixArr = new List<string>();
            StringBuilder sb = new StringBuilder();
            try
            {
                if (rgx.IsMatch(inputStr))
                {
                    //count no of 0's and 1's in string
                    foreach (var str in inputStr)
                    {
                        if (str.ToString() == "1")
                            noOfOnes++;
                        else if (str.ToString() == "0")
                            noOfZeros++;

                        //add new prefix to prefix array
                        sb.Append(str.ToString());
                        prefixArr.Add(sb.ToString());
                    }

                    //if no of 0's and 1's are equal than check for 
                    //For every prefix of the binary string, the number of 1's should not be less than the number of 0's.
                    if (noOfOnes == noOfZeros)
                    {
                        Console.WriteLine("Entered binary string contains equal no fo 0's and 1's.");

                        //prints all prefix for entered binary string
                        Console.WriteLine("Prefixes for given binary string are:");
                        foreach (var currentPrefix in prefixArr)
                        {
                            Console.WriteLine(currentPrefix);
                        }

                        Console.WriteLine("Now checking For every prefix of the binary string that the number of 1's should not be less than the number of 0's.");
                        foreach (var pre in prefixArr)
                        {
                            Console.WriteLine("Checking prefix: " + pre); //print msg

                            long noOfZerosInPrefix = 0;
                            long noOfOnesInPrefix = 0;
                            foreach (var p in pre)
                            {
                                if (p.ToString() == "1")
                                    noOfOnesInPrefix++;
                                else if (p.ToString() == "0")
                                    noOfZerosInPrefix++;
                            }

                            //check whether no of 1's is less than no of 0's or not
                            if (noOfOnesInPrefix < noOfZerosInPrefix)
                                return "Entered string is not a good binary string. Error occured during validation of prefix: " + pre;
                        }
                    }
                    else
                    {
                        return "No of 0's and no of 1's are not equals in entered binary string.";
                    }
                    return "Entered string is a good binary string";
                }
                else
                {
                    return "Entered string is not a valid binary string.";
                }
            }
            catch (Exception ex)
            {
                return "Error :" + ex.Message;
            }
        }
    }
}

Mongodb.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Mongodb.Web.Helpers;
using Mongodb.Web.Models;
using MongoDB.Bson;
using MongoDB.Driver;

namespace Mongodb.Web.Controllers
{
    public class HomeController : Controller
    {
        private IBookService _service;
        public HomeController(IBookService service)
        {
            _service = service;
        }

        public IActionResult Index()
        {
            var books = _service.Get();
            return View(books);
        }

        public IActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Insert(Book book)
        {
            _service.Create(book);
            TempData["Message"] = "Book added successfully!";
            return RedirectToAction("Index");
        }

        public IActionResult Update(string id)
        {          
            Book book = _service.Get(id);
            if (book == null)
            {
                return NotFound();
            }
            return View(book);
        }

        [HttpPost]
        public IActionResult Update(string id, Book bookIn)
        {
            var book = _service.Get(id);
            if (book == null)
            {
                return NotFound();
            }
            try
            {
                _service.Update(id, bookIn);
                TempData["Message"] = "Book updated successfully!";
            }
            catch
            {
                TempData["Message"] = "Error occured while updating Book!";
            }
            return RedirectToAction("Index");
        }
        
        public IActionResult Delete(string id)
        {
            var book = _service.Get(id);
            if (book == null)
            {
                return NotFound();
            }
            try
            {
                _service.Remove(book.Id);
                TempData["Message"] = "Book deleted successfully!";
            }
            catch
            {
                TempData["Message"] = "Error occuered while deleting Book!";
            }                    
            return RedirectToAction("Index");
        }

        public IActionResult Aggregate()
        {
            var result = _service.Aggregate();
            ViewBag.Message = "Perform Aggregate!";
            return View(result);          
        }
    }
}

Mongodb.Web/Views/Binary/Index.cshtml
@{
    ViewBag.Title = "Binary String";
}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <p>Check for a valid Binary String</p>
            <br />
            <form class="form-horizontal">
                <div class="form-group">
                    <label>Binary String</label>
                    <input type="text" class="form-control" id="txtInputStr" placeholder="Binary String" required />
                </div>
                <button type="button" class="btn btn-primary" id="btnSubmit">Submit</button>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/js/custom/binary/index.js"></script>
}

Mongodb.Web/Views/Home/Aggregate.cshtml
@model List<Mongodb.Web.Models.Aggregate>
@{
    ViewData["Title"] = "Aggregate";
}
<h1>@ViewData["Title"]</h1>

@section Styles{
    <link href="~/css/custom/home/index.css" rel="stylesheet" />
}

<h2>Aggregate on BookName with Max Price </h2>

<table class="table table-striped">
    <thead>
        <tr scope="col">         
            <th>BookName</th>
            <th>Total</th>          
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.BookName</td>
                <td>@item.Total</td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script src="~/js/custom/home/index.js"></script>
}

Mongodb.Web/Views/Home/Index.cshtml
@model List<Mongodb.Web.Models.Book>
@{
    ViewData["Title"] = "Home Page";
}
@section Styles{
    <link href="~/css/custom/home/index.css" rel="stylesheet" />
}

<h1>List of Books</h1>

@{
    string message = string.Empty;
    if (TempData["Message"] != null)
    {
        message = TempData["Message"].ToString();
        <div class="success-err-div">
            @if (message.ToUpper().Contains("SUCCESS"))
            {
                <span class="success-msg">@message</span>
            }
            else if (message.ToUpper().Contains("ERROR"))
            {
                <span class="error-msg">@message</span>
            }
        </div>
    }
}

<a asp-controller="Home" asp-action="Insert" class="btn btn-primary">Add New Book</a>
<br />
<br />

<table class="table table-striped">
    <thead>
        <tr>
            <th>Id</th>
            <th>BookName</th>
            <th>Author</th>
            <th>Category</th>
            <th>Price</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.BookName</td>
                <td>@item.Author</td>
                <td>@item.Category</td>
                <td>@item.Price</td>
                <td>
                    <a asp-controller="Home" asp-action="Update" asp-route-id="@item.Id" class="btn btn-info">Edit</a>
                    <a asp-controller="Home" asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger"> Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <script src="~/js/custom/home/index.js"></script>
}

Mongodb.Web/Views/Home/Insert.cshtml
@model Mongodb.Web.Models.Book

@{
    ViewData["Title"] = "Insert";
}
<h1>Insert Book</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-controller="Home" asp-action="Insert" method="post">
            <div class="form-group">
                <label for="exampleInputEmail1">Book ID</label>
                <input type="text" asp-for="Id" class="form-control" placeholder="Enter book id">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Book Name</label>
                <input type="text" asp-for="BookName" class="form-control" placeholder="Enter book name">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Author</label>
                <input type="text" asp-for="Author" class="form-control" placeholder="Enter book author">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <input type="text" asp-for="Category" class="form-control" placeholder="Enter book category">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Price</label>
                <input type="number" asp-for="Price" class="form-control" placeholder="Enter book price">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" placeholder="Enter book id">Save Book</button>
            </div>
        </form>
    </div>
</div>

Mongodb.Web/Views/Home/Update.cshtml
@model Mongodb.Web.Models.Book

@{
    ViewData["Title"] = "Update";
}

<h1>Update Book</h1>

<div class="row">
    <div class="col-md-6">
        <form asp-controller="Home" asp-action="Update" method="post">
            <input type="hidden" name="Id" value="@Model.Id.ToString()" />
            <div class="form-group">
                <label for="exampleInputEmail1">Book ID</label>
                <input type="text" asp-for="Id" class="form-control" placeholder="Enter book id">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Book Name</label>
                <input type="text" asp-for="BookName" class="form-control" placeholder="Enter book name">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Author</label>
                <input type="text" asp-for="Author" class="form-control" placeholder="Enter book author">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Category</label>
                <input type="text" asp-for="Category" class="form-control" placeholder="Enter book category">
            </div>
            <div class="form-group">
                <label for="exampleInputEmail1">Price</label>
                <input type="number" asp-for="Price" class="form-control" placeholder="Enter book price">
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary" placeholder="Enter book id">Update Book</button>
            </div>
        </form>
    </div>
</div>

Mongodb.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mongodb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @RenderSection("Styles", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mongodb</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Book Store</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Binary" asp-action="Index">Binary String</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Aggregate">Aggregate</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Mongodb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>